version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app



  db:
    image: postgres:14.0-alpine
    volumes:
      - ./postgres:/var/lib/postgres/data


